### ISSUE TITLE
Checkpoint not working

### ISSUE THREAD

**Issue by jedlennox** [hariszaf/pema#1]
Hello,

I've been testing out PEMA with my data for the past few days and have run into an issue.  I got it going, and all was fine until my job ran out of memory.  It was partway through the clustering step when this happened.  I wasn't too worried because I know PEMA has a checkpoint system I can use to restart at this point.  I am having issues doing this, however. 

I am running the code on a slurm controlled HPC cluster:

`singularity exec -B /nesi/nobackup/uoaxxxxx/PEMA/analysis_folder/:/mnt/analysis /nesi/nobackup/uoaxxxxx/PEMA/pema_latest.sif /home/tools/BDS/.bds/bds -r /nesi/nobackup/uoaxxxxx/PEMA/analysis_folder/trimming.chp`

and I get the error:

`Picked up JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport
Exception in thread "main" java.lang.RuntimeException: File not found '/nesi/nobackup/uoa02559/PEMA/analysis_folder/trimming.chp'
	at org.bds.util.Gpr.reader(Gpr.java:553)
	at org.bds.util.Gpr.reader(Gpr.java:534)
	at org.bds.serialize.BdsSerializer.load(BdsSerializer.java:271)
	at org.bds.Bds.runCheckpoint(Bds.java:886)
	at org.bds.Bds.run(Bds.java:853)
	at org.bds.Bds.main(Bds.java:185)`

I have tried with other checkpoint files also but with no luck. Am I being dense or should this restart the process at that stage?

Congrats on the pipeline and publication!

Thanks for your help,

Jed

**Comment by hariszaf** [comment]
Hello Jed and thank you very much for your kind comments! :) 

I just did some tests on the HPC I am using (Singularity v3.3.0-1) and the checkpoint files work just fine. 

I am about to make a **Hint for checkpoints** slide on the tutorial, as they need a special treatment in some cases. 

Jed could you check the version of Singularity that your HPC uses? 

In addition, does your code start to perform and then it stops or it does not start at all and you just get this error message? 

Haris

**Comment by jedlennox** [comment]
Hi Haris,

I can indeed tell you, I'm using Singularity 3.5.2. I also have the option of 3.4.0.  The code will immediately spit that error out (well after 4 - 7 seconds).  I also tried variations like not including the entire /nesi/.../... etc incase it was looking for a nesi folder in my analysis folder or anything like that.

Cheers,

Jed :)

**Comment by hariszaf** [comment]
And the error returned is the same in every case or just for the trimming.chp? 

You mentioned you tried several checkpoints. Do you always get the same error?

Haris

**Comment by jedlennox** [comment]
Yes, same error each time.  I tried the 'errorCorrection' checkpoint too and I got the same message within the same time frame.

Jed :)

**Comment by hariszaf** [comment]
Jed it is really awkward to me. 

Would you like to send me your skype id or something at my mail to run some tests together? 

My email address is: haris-zaf@hcmr.gr

**Comment by hariszaf** [comment]
It appears to be a path issue.
