### ISSUE TITLE
Fatal error: ./pema_latest.bds, line 446

### ISSUE THREAD

**Issue by ElhamKarimi** [hariszaf/pema#10]
Hello there,

I am reaching out for help regarding an error I am facing twice and I don't know what is exactly the problem and how to solve it. 

I am running my data using PEMA latest version through docker V 3.2.2 on mac OS V10.13.6

I have 100 samples and the problem is happing after 3 days and 5 hours of running approximately.
 the error  to me is timing out error ( perhaps I am mistaken! ) however, I copied the error below and I would be thankful if you could guide me on that.

Thanks in advance and looking forward to hearing from you

Best Regards,
Elham

SPAdes log can be found here: /mnt/analysis/pema_result_22April2021/3.correct_by_BayesHammer/ERR0000100/spades.log

Thank you for using SPAdes!
Error correction using BayesHammer is completed!
filtered_max_ERR0000011_1.fastq.gz.1P.fastq.00.0_0.cor.fastq.gz
filtered_max_ERR0000011_2.fastq.gz.2P.fastq.00.0_0.cor.fastq.gz
ERR	NOFILE	filtered_max_ERR0000011_1.fastq.gz.1P.fastq.00.0_0.cor.fastq.gz
Too confused to continue.
Try -h for help.
Task failed:
	Program & line     : './pema_latest.bds', line 444
	Task Name          : ''
	Task ID            : 'pema_latest.bds.20210422_075345_852/task.pema_latest.line_444.id_659'
	Task PID           : '55544'
	Task hint          : '/home/tools/PANDAseq/bin/pandaseq -f filtered_max_ERR0000011_1.fastq.gz.1P.fastq.00.0_0.cor.fastq.gz -r filtered_max_ERR0000011_2.fastq.gz.2P.fastq.00'
	Task resources     : 'cpus: 1	mem: -1.0 B	timeout: 86400	wall-timeout: 86400'
	State              : 'ERROR'
	Dependency state   : 'ERROR'
	Retries available  : '1'
	Input files        : '[]'
	Output files       : '[]'
	Script file        : '/home/pema_latest.bds.20210422_075345_852/task.pema_latest.line_444.id_659.sh'
	Exit status        : '1'
	StdErr (10 lines)  :
		ERR	NOFILE	filtered_max_ERR0000011_1.fastq.gz.1P.fastq.00.0_0.cor.fastq.gz
		Too confused to continue.
		Try -h for help.

Fatal error: ./pema_latest.bds, line 446, pos 4. Task/s failed.

Creating checkpoint file '/home/pema_latest.bds.line_446.chp'

**Comment by hariszaf** [comment]
Hi @ElhamKarimi . 

I just noticed that I had not replied to your issue. 

So now a quite different version of pema is available. 

If you 're interested in running i d be glad to help. 
My apologies for didn't get back to you earlier.
