### ISSUE TITLE
PEMA dependencies

### ISSUE THREAD

**Issue by deniskristak** [hariszaf/pema#13]
Hi,
I am currently trying to understand what your dockerfiles do and the installation using build-from-source approach, purpose of this being support by [EasyBuild](https://github.com/easybuilders/easybuild).
In my understanding, dockerfiles in `./pemabase` folder take care of environment (dependencies) and the `./Dockerfile.pema` does little more than just copying PEMA scripts to correct directories inside docker container.
Im guessing then, that it shouldn't be too hard to achieve what I'm trying to do, had I known all the dependencies.
Therefore, let me ask you, in case I did get the PEMA installation process correctly, have you, by any chance, got a list of dependencies, maybe containing even their required versions, other than those in pemabase Dockerfiles (since they are a tad harder to read and definitely not very specific)?
Thanks a lot for your answer! :-)

**Comment by hariszaf** [comment]
Hi @deniskristak ! 
Really sorry for the late reply! 
As you said, the `pemabase` image is what we have built as our environment, including all the software tools we need. 
Then, we build the `pema` image based on `pemabase` and including our pieces of code. 
The versions of the software included on pema are described at PEMA publication and as some of them have been updated it's a good idea to build a table or something to include them there. 
I ll do that asap and i ll let you know! 
Thanks for your interest on PEMA and sorry for the late reply!!

**Comment by boegel** [comment]
@hariszaf Thanks for the feedbak!

Any update on an overview of required dependencies for PEMA, or a better installation procedure that doesn't involve containers?

**Comment by hariszaf** [comment]
Hi @boegel ! 

Sorry for the late reply. 

I did not get the time to build a nice table or something, however I thought that you may find 
even better the Dockerfile for the image that PEMA uses as a base; as we had discussed, I first built the environment 
of PEMA as a Docker image and then I used this as the `base image` for the final PEMA docker image. 

So, by having a look at this [Dockerfile](https://github.com/hariszaf/pema/blob/master/pema_docker_image/pemabase/Dockerfile) you can 
check all the dependencies required. 

Sorry for the delay, I hope i ll do have a list soon. 
On June a new veresion ([v.2.1.3](https://github.com/hariszaf/pema/releases/tag/v.2.1.3)) was released, so you better check on this one for anything might be needed.

**Comment by hariszaf** [comment]
Hi @boegel, hi @deniskristak 

It has been a while but in case you are still interested in this issue, you may have a look at issue #28 
or/and the [`encapsulated_software.md`](https://github.com/hariszaf/pema/blob/ARMS/help_files/encapsulated_software.md) file. 

I will close this issue now, but if you need anything feel free to re-open or contact. 

Cheers
