### ISSUE TITLE
Getting an error  about '16S_otutab.txt': No such file or directory with the example

### ISSUE THREAD

**Issue by pradac** [hariszaf/pema#2]
Reading file all.nonchimeras.fasta 100%
1242678 nt in 4409 seqs, min 200, max 390, avg 282
Masking 100%
Sorting by abundance 100%
Counting k-mers 100%
Clustering 100%
Sorting clusters 100%
Writing clusters 100%
Clusters: 155 Size min 2, max 692, avg 28.4
Singletons: 0, 0.0% of seqs, 0.0% of clusters
Writing OTU table (classic) 100%
cp: cannot stat '16S_otutab.txt': No such file or directory
Fatal error: ./pema_latest.bds, line 694, pos 3. Exec failed.
	Exit value : 1
	Command    :  cp 16S_otutab.txt rna_otutab_its_taxon_assign.txt

**Comment by hariszaf** [comment]
Hi pradac,

sorry for the late response. 

what is the pema container you are running?
