### ISSUE TITLE
Conversion to ENA format - Sample names

### ISSUE THREAD

**Issue by cpavloud** [hariszaf/pema#23]
Using the current PEMA version (pema v.2.1.3), when choosing 
`EnaData	No`
the sequence files are converted to the necessary format for PEMA to run. 

During this conversion, they get new names such as ERR0000001, ERR0000002, ERR0000003 etc.

However, in the finalTable.tsv (and the other output files at the XXX_taxon_assign folder), the sample names are ERR1, ERR2, ERR3 etc.

**Comment by hariszaf** [comment]
That should not be like this.. 

@cpavloud  do you think the `finaTable.tsv` should have the `ERR000001` names or the initial ones.. ?

**Comment by cpavloud** [comment]
I think it should have the `ERR000001` names, because this is what all the intermediate files have.

**Comment by hariszaf** [comment]
Ok cool. I ll fix that asap

**Comment by hariszaf** [comment]
Issue resolved thanks to commit [a0175fcd3e](https://github.com/hariszaf/pema/commit/a0175fcd3ee8a222f1d51b6aa663449876f171c4).

Names in both finalTable and in the previous steps are named accroding to the mapping file
