### ISSUE TITLE
Empty 8.outputPerSample folder

### ISSUE THREAD

**Issue by cpavloud** [hariszaf/pema#25]
When I am running 16S data with the vsearch algorithm using the current version of PEMA (pema v.2.1.3), the "8.outputPerSample" folder is empty.
I haven't tried it yet with other genes/sets of parameters to see if the error is being repeated.

**Comment by hariszaf** [comment]
It is now working for the cases that CREST classifier is used. 

I ll fix it for the case of RDP once COI oriented bugs are fixed

**Comment by hariszaf** [comment]
Issue resolved thanks to commit [a0175fcd3e](https://github.com/hariszaf/pema/commit/a0175fcd3ee8a222f1d51b6aa663449876f171c4).

Names in both finalTable and in the previous steps are named accroding to the mapping file

**Comment by hariszaf** [comment]
@cpavloud  this issue is now resolved for all cases. 
if you can think of any other info that would be of help for the user at this level, feel free to reopen the issue.
