### ISSUE TITLE
ITS sanity check fails

### ISSUE THREAD

**Issue by probonas** [hariszaf/pema#34]
Running PEMA for the ITS sample under /sanity_checks with the given parameters file fails with the following message:

> mv: target 'data_after_cutadapt/' is not a directory
Fatal error: ./pema_latest.bds, line 342, pos 5. Exec failed.
	Exit value : 1
	Command    :  mv *fastq.gz data_after_cutadapt/

**Comment by hariszaf** [comment]
Hi @probonas ! 
Thanks for letting me know. 
I will check on that and reply asap
