### ISSUE TITLE
 custom_ref_db doesn't work.

### ISSUE THREAD

**Issue by hyeiny119** [hariszaf/pema#50]
When I analyze 18S using my custom_ref_db, I get this error. 
![image](https://user-images.githubusercontent.com/36435306/217395740-53758c65-fcfc-488d-a43d-eb1621e927ff.png)

This is the parameter and custom db I made. 
[parameters.txt](https://github.com/hariszaf/pema/files/10680468/parameters.txt) (Original file name is "parameters.tsv")
[hikim_test_SSEQ.nds.txt](https://github.com/hariszaf/pema/files/10680481/hikim_test_SSEQ.nds.txt)  (Original file name is "hikim_test_SSEQ.nds")
[hikim_test.fasta.txt](https://github.com/hariszaf/pema/files/10680541/hikim_test.fasta.txt) (Original file name is "hikim_test.fasta")

So, I tested your "crest_algo_example" (http://pema/analysis_directory/custom_ref_db/crest_algo_example/).
Even if I use the crest example file you uploaded, I get the same error.
![image](https://user-images.githubusercontent.com/36435306/217396626-9fb396bb-fef8-40b3-a137-fbd78a111c01.png)
I have my doubts about whether your example files work well.

So what to ask for
1. Is it possible to get .fasta and .nds file of silva 132 embeded in PEMA.
2. Is it possible to get an crest example of using custom_ref_db correctly (parameters and custom db).

Thank you!

**Comment by hariszaf** [comment]
Hi @hyeiny119. 

Could you please also share the pema version you re using just to make sure what to look for. 

Thanks for your interest on `pema`.

**Comment by hariszaf** [comment]
In addition, could you also send me the log you had until the end of it ? 
It is my belief that the training is going fine and the issue is a bit later.

**Comment by hyeiny119** [comment]
Thank you for your prompt response. 
I used pema v.2.1.4.
This is full logs. And I use this command line. "nohup docker run -i -v /hikim/app/project/PEMA_18S/PRJNA525566_MOCK1_vsearch_dbtest2:/mnt/analysis hariszaf/pema:v.2.1.4 ./pema_latest.bds > /hikim/app/project/PEMA_18S/PRJNA525566_MOCK1_vsearch_dbtest2/crest_algo_example.log &"

[crest_algo_example.log](https://github.com/hariszaf/pema/files/10691660/crest_algo_example.log)
[hikim-custom.log](https://github.com/hariszaf/pema/files/10691662/hikim-custom.log)

Thank you hariszf !!

**Comment by hariszaf** [comment]
@hyeiny119 thanks a lot for the feedback! 

I have spotted what's the issue here and I ll try to make a new `pema` release by this weekend to address this. 

Thanks again and I will let you know once the release is out!

**Comment by hariszaf** [comment]
Hi @hyeiny119, 

would you like to give it a shot with `v.2.1.5` ?  You may get this by running :

``` 
docker pull hariszaf/pema:v.2.1.5 
```

FYI, for the time being, this version is available only as a Docker image. 

Could you give it a shot and give us your feedback? Thanks again! :smiley:
