### ISSUE TITLE
Unexpected Singletons in Final Table despite removeSingletons set to "Yes"

### ISSUE THREAD

**Issue by JustinePa** [hariszaf/pema#58]
**Issue**
When setting the "removeSingletons" parameter to "Yes" in PEMA, I'm noticing that many singletons still appear in the final output table (often hundreds of them towards the end of the table) while they should not be there.

**Details**
I am using PEMA version 2.1.4, running it on ARMS data using the LifeWatch workflow on the Tesseract platform.

It would be appreciated if this behavior could be looked into, as it's crucial for the accuracy of our analyses to ensure that unwanted singletons are excluded when specified.

Thank you!

**Comment by hariszaf** [comment]
Hi @JustinePa ! 

Could you share your parameters file ?

**Comment by JustinePa** [comment]
Hi,

Sure, here it is: [PemaParameters_v214_COI_2023 - Copy.txt](https://github.com/hariszaf/pema/files/12426969/PemaParameters_v214_COI_2023.-.Copy.txt)

**Comment by hariszaf** [comment]
Hi, it seems we have forgot to update the parameters file in the analysis folder.
I ll fix that asap.

If you are using the latest version of pema 2.1.4, then you should use this parameters file 
https://github.com/hariszaf/pema/blob/master/pema_docker_image/sanity_check/COI/parameters.tsv

Notice that there are now two parameters you need, the removeOligotons and another one for their number you d like to remove e.g doubleton

**Comment by JustinePa** [comment]
Thank you, I will try this!

**Comment by hariszaf** [comment]
Great!
Give it a shot and please let me know if everything went fine 🚀
