### ISSUE TITLE
why this Fatal error: /home/pema_latest.bds, line 175, pos 1. Task/s failed

### ISSUE THREAD

**Issue by Akhilbiju01** [hariszaf/pema#6]
I run the tutorial command in step 3 singularity run -B /root/Desktop/pema/analysis_directory/:/mnt/analysis /root/Desktop/pema_v.1.3.1.sif
Approx 95% complete for SRR3231901_1.fastq.gz
Analysis complete for SRR3231901_1.fastq.gz
Task failed:
        Program & line     : '/home/pema_latest.bds', line 173
        Task Name          : ''
        Task ID            : 'pema_latest.bds.20201123_083118_572/task.pema_latest.line_173.id_6'
        Task PID           : '561'
        Task hint          : '/home/tools/fastqc/FastQC/fastqc --outdir /mnt/analysis/16S_final_test/1.quality_control  /mnt/analysis/mydata/README.md'
        Task resources     : 'cpus: 1   mem: -1.0 B     timeout: 86400  wall-timeout: 86400'
        State              : 'ERROR'
        Dependency state   : 'ERROR'
        Retries available  : '1'
        Input files        : '[]'
        Output files       : '[]'
        Script file        : '/root/Desktop/pema_latest.bds.20201123_083118_572/task.pema_latest.line_173.id_6.sh'
        Exit status        : '1'
        StdErr (10 lines)  :
                Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
                Failed to process /mnt/analysis/mydata/README.md
                uk.ac.babraham.FastQC.Sequence.SequenceFormatException: ID line didn't start with '@'
                        at uk.ac.babraham.FastQC.Sequence.FastQFile.readNext(FastQFile.java:158)
                        at uk.ac.babraham.FastQC.Sequence.FastQFile.<init>(FastQFile.java:89)
                        at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:106)
                        at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:62)
                        at uk.ac.babraham.FastQC.Analysis.OfflineRunner.processFile(OfflineRunner.java:152)
                        at uk.ac.babraham.FastQC.Analysis.OfflineRunner.<init>(OfflineRunner.java:121)
                        at uk.ac.babraham.FastQC.FastQCApplication.main(FastQCApplication.java:316)

Fatal error: /home/pema_latest.bds, line 175, pos 1. Task/s failed.
pema_latest.bds, line 175 :     wait

**Comment by Tclack88** [comment]
@Akhilbiju01 Did you remove any non fastq.gz files? I've found I got the same error (though line 161's "wait") before I removed the README.md. Given we had different lines, that's a little strange, but check for the presence of any non-relevant files

**Comment by hariszaf** [comment]
Hi there, 

@Tclack88 is probably right. 

On the ```mydata``` directory you need to include **only** your ```.fastq.gz``` files.

**Comment by Akhilbiju01** [comment]
@Tclack88 As you had mentioned I removed the README.md. just include .fasta.gz files in mydata directory. now im get an error in line 366. do I have to install SPAdes to rectify this problem if so can you let the correct installation procedure
singularity run -B /root/Desktop/pema/analysis_directory/:/mnt/analysis /root/Desktop/pema_v.1.3.1.sif
Picked up JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true

this ouput file already exists
SRR3231900_1.fastq.gzSRR3231900_2.fastq.gzPicked up JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Started analysis of SRR3231900_1.fastq.gz
Approx 5% complete for SRR3231900_1.fastq.gz
Approx 10% complete for SRR3231900_1.fastq.gz
Approx 15% complete for SRR3231900_1.fastq.gz
Picked up JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Started analysis of SRR3231900_2.fastq.gz
Approx 5% complete for SRR3231900_2.fastq.gz
Approx 10% complete for SRR3231900_2.fastq.gz
Approx 15% complete for SRR3231900_2.fastq.gz
Approx 20% complete for SRR3231900_1.fastq.gz
Approx 25% complete for SRR3231900_1.fastq.gz
Approx 30% complete for SRR3231900_1.fastq.gz
Approx 20% complete for SRR3231900_2.fastq.gz
Approx 25% complete for SRR3231900_2.fastq.gz
Approx 30% complete for SRR3231900_2.fastq.gz
Approx 35% complete for SRR3231900_1.fastq.gz
Approx 40% complete for SRR3231900_1.fastq.gz
Approx 45% complete for SRR3231900_1.fastq.gz
Approx 35% complete for SRR3231900_2.fastq.gz
Approx 40% complete for SRR3231900_2.fastq.gz
Approx 45% complete for SRR3231900_2.fastq.gz
Approx 50% complete for SRR3231900_1.fastq.gz
Approx 55% complete for SRR3231900_1.fastq.gz
Approx 60% complete for SRR3231900_1.fastq.gz
Approx 65% complete for SRR3231900_1.fastq.gz
Approx 50% complete for SRR3231900_2.fastq.gz
Approx 55% complete for SRR3231900_2.fastq.gz
Approx 60% complete for SRR3231900_2.fastq.gz
Approx 70% complete for SRR3231900_1.fastq.gz
Approx 75% complete for SRR3231900_1.fastq.gz
Approx 65% complete for SRR3231900_2.fastq.gz
Approx 70% complete for SRR3231900_2.fastq.gz
Approx 75% complete for SRR3231900_2.fastq.gz
Approx 80% complete for SRR3231900_1.fastq.gz
Approx 85% complete for SRR3231900_1.fastq.gz
Approx 90% complete for SRR3231900_1.fastq.gz
Approx 80% complete for SRR3231900_2.fastq.gz
Approx 85% complete for SRR3231900_2.fastq.gz
Approx 90% complete for SRR3231900_2.fastq.gz
Approx 95% complete for SRR3231900_2.fastq.gz
Analysis complete for SRR3231900_2.fastq.gz
Analysis complete for SRR3231900_1.fastq.gz
Approx 95% complete for SRR3231900_1.fastq.gz
FastQC is completed!
readF is: SRR3231900_1.fastq.gz
readR is: SRR3231900_2.fastq.gz
You hace selected Max INFO
Picked up JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
TrimmomaticPE: Started with arguments:
 -threads 8 -trimlog TrimLog /mnt/analysis/mydata/SRR3231900_1.fastq.gz /mnt/analysis/mydata/SRR3231900_2.fastq.gz /mnt/analysis/16S_final_test/2.trimmomatic_output/filtered_max_SRR3231900_1.fastq.gz.1P.fastq.gz /mnt/analysis/16S_final_test/2.trimmomatic_output/filtered_max_SRR3231900_1.fastq.gz.1U.fastq.gz /mnt/analysis/16S_final_test/2.trimmomatic_output/filtered_max_SRR3231900_2.fastq.gz.2P.fastq.gz /mnt/analysis/16S_final_test/2.trimmomatic_output/filtered_max_SRR3231900_2.fastq.gz.2U.fastq.gz ILLUMINACLIP://home/tools/Trimmomatic/Trimmomatic-0.38/adapters/TruSeq2-PE.fa:0:20:30 LEADING:20 TRAILING:2 MAXINFO:100:0.8 MINLEN:100
Using PrefixPair: 'AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT' and 'CAAGCAGAAGACGGCATACGAGATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT'
Using Long Clipping Sequence: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT'
Using Long Clipping Sequence: 'AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTTG'
Using Long Clipping Sequence: 'TTTTTTTTTTAATGATACGGCGACCACCGAGATCTACAC'
Using Long Clipping Sequence: 'TTTTTTTTTTCAAGCAGAAGACGGCATACGA'
Using Long Clipping Sequence: 'CAAGCAGAAGACGGCATACGAGATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT'
Using Long Clipping Sequence: 'AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT'
ILLUMINACLIP: Using 1 prefix pairs, 6 forward/reverse sequences, 0 forward only sequences, 0 reverse only sequences
Quality encoding detected as phred33
Input Read Pairs: 39248 Both Surviving: 39248 (100.00%) Forward Only Surviving: 0 (0.00%) Reverse Only Surviving: 0 (0.00%) Dropped: 0 (0.00%)
TrimmomaticPE: Completed successfully
Trimmomatic  is done

trimCheck: filtered_max_SRR3231900
newDir: SRR3231900
/bin/gzip
gzip 1.6
Copyright (C) 2007, 2010, 2011 Free Software Foundation, Inc.
Copyright (C) 1993 Jean-loup Gailly.
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

Written by Jean-loup Gailly.
readBayesF: filtered_max_SRR3231900_1.fastq.gz.1P.fastq.gz
and readBayesR: filtered_max_SRR3231900_2.fastq.gz.2P.fastq.gz
Command line: /home/tools/SPAdes/SPAdes-3.13.0-Linux/bin/spades.py      --only-error-correction --threads       8-o       /mnt/analysis/16S_final_test/3.correct_by_BayesHammer/SRR3231900        -1      /mnt/analysis/16S_final_test/2.trimmomatic_output/filtered_max_SRR3231900_1.fastq.gz.1P.fastq.gz  -2      /mnt/analysis/16S_final_test/2.trimmomatic_output/filtered_max_SRR3231900_2.fastq.gz.2P.fastq.gz  --disable-gzip-output

System information:
  SPAdes version: 3.13.0
  Python version: 2.7.12
  OS: Linux-4.19.128-microsoft-standard-x86_64-with-Ubuntu-16.04-xenial

Output dir: /mnt/analysis/16S_final_test/3.correct_by_BayesHammer/SRR3231900
Mode: ONLY read error correction (without assembling)
Debug mode is turned OFF

Dataset parameters:
  Multi-cell mode (you should set '--sc' flag if input data was obtained with MDA (single-cell) technology or --meta flag if processing metagenomic dataset)
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/mnt/analysis/16S_final_test/2.trimmomatic_output/filtered_max_SRR3231900_1.fastq.gz.1P.fastq.gz']
      right reads: ['/mnt/analysis/16S_final_test/2.trimmomatic_output/filtered_max_SRR3231900_2.fastq.gz.2P.fastq.gz']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will NOT be compressed
Other parameters:
  Dir for temp files: /mnt/analysis/16S_final_test/3.correct_by_BayesHammer/SRR3231900/tmp
  Threads: 8
  Memory limit (in Gb): 6


======= SPAdes pipeline started. Log can be found here: /mnt/analysis/16S_final_test/3.correct_by_BayesHammer/SRR3231900/spades.log


===== Read error correction started. 


== Running read error correction tool: /home/tools/SPAdes/SPAdes-3.13.0-Linux/bin/spades-hammer /mnt/analysis/16S_final_test/3.correct_by_BayesHammer/SRR3231900/corrected/configs/config.info

The program was terminated by segmentation fault
=== Stack Trace ===


== Error ==  system call for: "['/home/tools/SPAdes/SPAdes-3.13.0-Linux/bin/spades-hammer', '/mnt/analysis/16S_final_test/3.correct_by_BayesHammer/SRR3231900/corrected/configs/config.info']" finished abnormally, err code: -11

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.
Task failed:
        Program & line     : '/home/pema_latest.bds', line 364
        Task Name          : ''
        Task ID            : 'pema_latest.bds.20201212_071334_321/task.pema_latest.line_364.id_13'
        Task PID           : '811'
        Task hint          : '/home/tools/SPAdes/SPAdes-3.13.0-Linux/bin/spades.py --only-error-correction --threads 8 -o /mnt/analysis/16S_final_test/3.correct_by_BayesHammer/SRR3'
        Task resources     : 'cpus: 1   mem: -1.0 B     timeout: 86400  wall-timeout: 86400'
        State              : 'ERROR'
        Dependency state   : 'ERROR'
        Retries available  : '1'
        Input files        : '[]'
        Output files       : '[]'
        Script file        : '/root/Desktop/pema_latest.bds.20201212_071334_321/task.pema_latest.line_364.id_13.sh'
        Exit status        : '1'
        StdOut (10 lines)  :

                The program was terminated by segmentation fault
                === Stack Trace ===


                == Error ==  system call for: "['/home/tools/SPAdes/SPAdes-3.13.0-Linux/bin/spades-hammer', '/mnt/analysis/16S_final_test/3.correct_by_BayesHammer/SRR3231900/corrected/configs/config.info']" finished abnormally, err code: -11

                In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
                or report an issue on our GitHub repository github.com/ablab/spades
                Please provide us with params.txt and spades.log files from the output directory.

Fatal error: /home/pema_latest.bds, line 366, pos 3. Task/s failed.
pema_latest.bds, line 325 :     for ( string trimmed : finalTrimos ) {
pema_latest.bds, line 336 :             if ( readBayesF.isEmpty() == false && readBayesR.isEmpty() == false ) {
pema_latest.bds, line 366 :                     wait

**Comment by hariszaf** [comment]
On the PEMA containers, all software needed are included so you don't need to install anything at all. 

Could you give some info for the environment you are trying to run pema on ? 

Is it a persnal computer? If yes, what OS are you working on?

**Comment by Akhilbiju01** [comment]
I'm using kali Linux os in wsl 2 in windows 10. I'm using my Insitute system,

**Comment by hariszaf** [comment]
Ok. 

That is the problem..

In the first place, I thought this was probably either a memory (RAM) error or an I/O one.

Then I found that SPAdes "[do not support Linux subsystem on Windows, it is known to contain bugs.](https://github.com/ablab/spades/issues/156)" 

However, as you can see in the same thread it seems they do run on this environment too..

Could you provide me with the ```params.txt``` and  ```spades.log``` files?

Sorry for that, but it is rather a SPAdes-specific issue.. Hope if you send me these files, I could help somehow. 

You can always give it a try in a different OS if available

**Comment by Akhilbiju01** [comment]
ok thanks, I will try to run with a different os and will update you

**Comment by hariszaf** [comment]
thank you very much for the feedback!
i am working on the code tryin to find a way to solve this as it is not the first time someone had this issue!
thanks again!
