### ISSUE TITLE
Long recurrent taxonomic labels

### ISSUE THREAD

**Issue by stas-malavin** [hariszaf/pema#68]
Hi @hariszaf ,
The dev version (2.1.5) produces very long recurrent taxonomy labels like this one:
```
Main genome;Eukaryota;Excavata;Discoba;Kinetoplastea;Kinetoplastea (class);X (Kinetoplastea (class));Kinetoplastea (X (Kinetoplastea (class)));XX (Kinetoplastea (X (Kinetoplastea (class))));Kinetoplastea (XX (Kinetoplastea (X (Kinetoplastea (class)))));XXX (Kinetoplastea (XX (Kinetoplastea (X (Kinetoplastea (class))))));Kinetoplastea (XXX (Kinetoplastea (XX (Kinetoplastea (X (Kinetoplastea (class)))))));XXX (Kinetoplastea (XXX (Kinetoplastea (XX (Kinetoplastea (X (Kinetoplastea (class))))))));sp. (XXX (Kinetoplastea (XXX (Kinetoplastea (XX (Kinetoplastea (X (Kinetoplastea (class)))))))))
```
```Main genome``` may be irrelevant, as well.

**Comment by hariszaf** [comment]
Hi @stas-malavin 
This is not a PEMA-related issue in my opinion. 
This is how the taxonomy database under used were set. 
You may deal with the taxonomy as you think it suits you best. 
You can also train the classifiers used in pema to use other databases as well. 
As this is not an issue i'd suggest we close this and discuss further the database issues on [gitter](https://app.gitter.im/#/room/#pema-helpdesk_community:gitter.im). 
Especially if you have arguments for or against a specific database it would be really nice to share.
